# RUTAS DE USUARIO #

user:
    path: /user
    controller: App\Controller\UserController::index
    methods: [POST]

user_create:
    path: /user/create
    controller: App\Controller\UserController::create
    methods: [POST]

user_login:
    path: /user/login
    controller: App\Controller\UserController::login
    methods: [POST]

user_edit:
    path: /user/edit
    controller: App\Controller\UserController::edit
    methods: [PUT]

# RUTAS DE POST #

post:
    path: /post
    controller: App\Controller\PostController::index
    methods: [POST]
post_show:
    path: /{slug}
    controller: App\Controller\PostController::show
    methods: [POST] 
post_new:
    path: /post/new
    controller: App\Controller\PostController::new
    methods: [POST]       